### ISSUE TITLE
How to use properly the XRandR library functions?

### ISSUE THREAD

**Issue by jokogr** [xmonad/X11#38]
Hello,

Could anyone make an example of using the XRandR bindings?

I have started making a small clone of the "xrandr -q" command:
```haskell
import Graphics.X11.Xlib
import Graphics.X11.Xrandr

main = do
  dpy <- openDisplay ""
  let dflt = defaultScreen dpy
  root <- rootWindow dpy dflt
  sc <- xrrGetScreenInfo dpy root
  sizes <- xrrConfigSizes sc
```

Is the code moving to the right direction?

Thanks in advance

**Comment by jokogr** [comment]
I think the code should be similar to this one, the original in C: http://cgit.freedesktop.org/xorg/app/xrandr/tree/xrandr.c

**Comment by jokogr** [comment]
ok, I have written the following:

```haskell
import Graphics.X11.Xlib
import Graphics.X11.Xrandr

maybeXrrConfigSizes :: Maybe XRRScreenConfiguration -> IO (Maybe [XRRScreenSize])
maybeXrrConfigSizes mc = case mc of
  Nothing -> do
    return Nothing
  Just c -> xrrConfigSizes c

maybeXrrScreenSize :: Maybe [XRRScreenSize] -> [XRRScreenSize]
maybeXrrScreenSize ms = case ms of
  Nothing -> []
  Just s -> s

main = do
  dpy <- openDisplay ""
  let dflt = defaultScreen dpy
  root <- rootWindow dpy dflt
  sc <- xrrGetScreenInfo dpy root
  sizes <- maybeXrrConfigSizes sc
  putStrLn $ show $ maybeXrrScreenSize sizes
```

Although the code compiles, I getting a segmentation fault.

**Comment by geekosaur** [comment]
Sounds like xrrGetScreenInfo is not checking for NULL on return (there is a *lot* of this in the X11 bindings, sadly) so it cores when you try to access the information returned from C.

**Comment by jokogr** [comment]
It appears I was not using properly the functions. After reading more carefully xrandr.c I have managed to write proper code which does not segfault.

**Comment by thedward** [comment]
@jokogr would you be willing you share your working code? I'm currently struggling with the same thing.

**Comment by jokogr** [comment]
@thedward sure, have a look [here](https://git.joko.gr/joko/dotfiles/src/linux-workstation/home/.xmonad/lib/MainMonitor.hs).

Bear in mind that I have replaced this code with the XRRGetMonitors bindings that I have proposed with [a pull request](https://github.com/xmonad/X11/pull/42) in this repository.
