### ISSUE TITLE
Any planned newer Hackage releases?

### ISSUE THREAD

**Issue by jameshfisher** [xmonad/X11#39]
The latest release on Hackage is from May 2014, over a year and a half ago. Is another release planned?

There's some stuff on `master` which is not released. For example, the one example in the `examples/` directory doesn't compile with the latest version on Hackage, but that example is over a year old.

**Comment by ikv** [comment]
Please do

**Comment by pjones** [comment]
We're working on a new release of xmonad, which means this package will also see a release really soon.

**Comment by pjones** [comment]
@dmwit I believe X11-1.7 is ready for release.  Do you mind if I tag it and upload to hackage?

**Comment by pjones** [comment]
1.7 has been uploaded to hackage.
