### ISSUE TITLE
Cabal build does not actually use the library search paths that Autoconf has found

### ISSUE THREAD

**Issue by bonds** [xmonad/X11#53]
EDIT: Autoconf successfully determines the necessary `-L` search paths, but Cabal does not actually use them. See https://github.com/xmonad/X11/issues/53#issuecomment-525567241 for details.

error:

````
    /usr/bin/ld: cannot find -lXss
````

full log below

````
[...]
````

Using Stackage [LTS 6.35](https://www.stackage.org/lts-6.35) which points at X11 v1.6.1.2 everything works just fine and X11 successfully compiles. Using the newer Stackage LTS 9.0 which points at X11 v1.8, I get the above error and cannot complete the compile.

**Comment by geekosaur** [comment]
Can you find out what openbsd calls the X screensaver extension client library? The includes for it appear tp be present, from the build output.

**Comment by geekosaur** [comment]
And it's a good question why configure only tests for the headers and not the associated libraries... we inherited this beast and it has a number of flaws, some of which we're already trying to fix. cc @pjones

**Comment by bonds** [comment]
Here is the X screensaver extension client library code for OpenBSD, via web cvs: 

- https://cvsweb.openbsd.org/cgi-bin/cvsweb/xenocara/lib/libXScrnSaver/
- https://cvsweb.openbsd.org/cgi-bin/cvsweb/~checkout~/xenocara/lib/libXScrnSaver/include/X11/extensions/scrnsaver.h?rev=1.2&content-type=text/plain

On a running OpenBSD 6.1-stable-amd64 system, I find ````scrnsaver.h```` in ````/usr/X11R6/include/X11/extensions````:

````
/u/X/i/X/extensions ❯❯❯ pwd                                                 Wed 2017-08-02 07:35:14 -0700
/usr/X11R6/include/X11/extensions
/u/X/i/X/extensions ❯❯❯ ls                                                  Wed 2017-08-02 07:35:47 -0700
EVI.h            XLbx.h           Xxf86dga.h       fontcache.h      render.h         xf86dga.h
EVIproto.h       XRes.h           ag.h             fontcacheP.h     renderproto.h    xf86dga1.h
MITMisc.h        XResproto.h      agproto.h        fontcachstr.h    saver.h          xf86dga1const.h
XEVI.h           XShm.h           bigreqsproto.h   ge.h             saverproto.h     xf86dga1proto.h
XI.h             XTest.h          bigreqstr.h      geproto.h        scrnsaver.h      xf86dga1str.h
XI2.h            Xag.h            composite.h      lbx.h            secur.h          xf86dgaconst.h
XI2proto.h       Xcomposite.h     compositeproto.h lbxproto.h       security.h       xf86dgaproto.h
XInput.h         Xcup.h           cup.h            mitmiscconst.h   securproto.h     xf86dgastr.h
XInput2.h        Xdamage.h        cupproto.h       mitmiscproto.h   shape.h          xf86misc.h
XIproto.h        Xdbe.h           damageproto.h    multibuf.h       shapeconst.h     xf86mscstr.h
XKB.h            Xext.h           damagewire.h     multibufconst.h  shapeproto.h     xf86vm.h
XKBbells.h       Xfixes.h         dbe.h            multibufproto.h  shm.h            xf86vmode.h
XKBconfig.h      Xge.h            dbeproto.h       panoramiXext.h   shmproto.h       xf86vmproto.h
XKBfile.h        Xinerama.h       dmx.h            panoramiXproto.h sync.h           xf86vmstr.h
XKBgeom.h        Xrandr.h         dmxext.h         presentproto.h   syncconst.h      xfixesproto.h
XKBproto.h       Xrender.h        dmxproto.h       presenttokens.h  syncproto.h      xfixeswire.h
XKBrules.h       Xv.h             dpms.h           randr.h          vldXvMC.h        xtestconst.h
XKBsrv.h         XvMC.h           dpmsconst.h      randrproto.h     xcmiscproto.h    xtestext1.h
XKBstr.h         XvMClib.h        dpmsproto.h      record.h         xcmiscstr.h      xtestext1const.h
XKBui.h          XvMCproto.h      dri2proto.h      recordconst.h    xf86bigfont.h    xtestext1proto.h
XKM.h            Xvlib.h          dri2tokens.h     recordproto.h    xf86bigfproto.h  xtestproto.h
XKMformat.h      Xvproto.h        extutil.h        recordstr.h      xf86bigfstr.h
````

does that help, or do you need something else?

**Comment by geekosaur** [comment]
It found scrnsaver.h, that's why it was trying to use the extension. What
it couldn't find was -lXss (aka libXss.a or libXss.so), the library
corresponding to the header.

**Comment by bonds** [comment]
Got it. Those are in /usr/X11R6/lib

````
~ ❯❯❯ ls -alh /usr/X11R6/lib/ | grep -i Xss                                 Wed 2017-08-02 12:22:32 -0700
-rw-r--r--  1 root  bin     9.7K Apr  1 13:05 libXss.a
-rw-r--r--  1 root  bin     976B Apr  1 12:53 libXss.la
-rw-r--r--  1 root  bin    16.7K Apr  1 12:53 libXss.so.6.0
````

**Comment by geekosaur** [comment]
Sorry for delay, I am mostly offline at the moment.

I think all you need is --extra-lib-dirs=/usr/X11R6/lib to get it to link.
>
>

-- 
brandon s allbery kf8nh                               sine nomine associates
allbery.b@gmail.com                                  ballbery@sinenomine.net
unix, openafs, kerberos, infrastructure, xmonad        http://sinenomine.net

**Comment by bonds** [comment]
Thanks! That seems to have worked. Now its in PR form: #54

**Comment by peti** [comment]
This is not a bug in `X11`. It's the user's resonsibility to provide the proper environment in which system libraries can be found, I'm afraid. We cannot possible know what those paths are and depend on the user to configure the build properly.

**Comment by blackgnezdo** [comment]
To be completely clear, is the value determined by `configure` not supposed to be used by `cabal`? 

I've added a flag to OpenBSD ports. It's just whoever aspires to use `cabal` directly won't get the same benefit.

**Comment by peti** [comment]
> To be completely clear, is the value determined by `configure` not supposed to be used by `cabal`?

Oh, sorry, I misunderstood that part of the ticket. No, that is not supposed to be happening.
