### ISSUE TITLE
XScreenSaver module API depends on build environment

### ISSUE THREAD

**Issue by nomeata** [xmonad/X11#59]
The XScreenSaver module originated from the arbtt tool. Upon import into X11 some CPP was added that implements it only partially: https://github.com/xmonad/X11/commit/ac3933e46e52fe10d875d673be5d7aec46f6de65#diff-0ede912a7989c1eb8640f56e67add449

If the header files are not present, then only `compiledWithXScreenSaver` exists in the module. But this does not work! A program that wants to make optional use of `XScreenSaver` will still reference the other functions. So if this module really should be optional, then it still needs to export all the functions (with dummy implementations).

Why do I only report this now? Because someone suggested that `arbtt` should start using `X11`’s implementation: https://github.com/nomeata/arbtt/commit/8ccde60b4cb679ae1614c6fedbc89719fa898ac4

But now people get build failures when `X11` was compiled without `XScreenSaver`, e.g. https://bitbucket.org/nomeata/arbtt/pull-requests/3/getxidletime-not-available/diff or https://github.com/nomeata/arbtt/pull/13

The whole conditional build thing is fishy anyways. I suggest that either you simply require these extensions, or the module is moved into its own package.

**Comment by geekosaur** [comment]
FWIW I made the same argument with respect to the Xinerama/XRandR module, and was informed that somehow this logic is incorrect and the current setup is "correct". I still do not understand the claimed justification, and regard it as a bug.

**Comment by nomeata** [comment]
I keep getting user complaints whose build fails. Can we make a decision how to proceed there? I see these options
 * The extension becomes non-optional
 * The module moves to its own package.
 * None of them, and my program will revert to a embedded copy of the module.

**Comment by dmwit** [comment]
The extension should be non-optional. Do you want to have commit bit and make it happen? I'll be happy to add you.

**Comment by nomeata** [comment]
I gave it a shot at https://github.com/xmonad/X11/pull/61

**Comment by nomeata** [comment]
Can we have a release with this fix? My users still face build errors.

**Comment by dmwit** [comment]
I'm happy enough to bump to 1.9 and release. Looks like xmonad (the other big customer) still builds fine assuming you can get X11 built at all with its new dependency, so that's fine; and anyway it has X11<1.9 in its build-depends. Even so, I'm paranoid, so I'm checking in with the xmonad maintainer for objections; if I don't get any in the next three days I'll make a release.

**Comment by dmwit** [comment]
Released. Thanks for the reminders.
