### ISSUE TITLE
New release needed to support ghc 8.8.1

### ISSUE THREAD

**Issue by peti** [xmonad/X11#66]
@dmwit, would you mind uploading the current `master` branch as a new release to Hackage? We need an update to support building with Cabal 3.0.x, which is shipped with ghc 8.8.1 by default. I pushed the necessary fixes already and updated https://travis-ci.org/xmonad/X11 to include the 8.8.x compiler.

**Comment by dmwit** [comment]
Yes, sure, it's done. Looking at the commits, it seems the main changes are bugfixes and compatibility issues, so I bumped the version to just 1.9.1.

You should also have the permissions you need to upload yourself in the future if you want.

**Comment by peti** [comment]
Hi Daniel,

> You should also have the permissions you need to upload yourself in
> the future if you want.

I checked a minute ago, and I do not have maintainer permissions on
Hackage. I -- <https://hackage.haskell.org/user/PeterSimons> -- am a
maintainer on Github, so I can commit and tag, but I cannot upload the
release at the moment.

Best regards,
Peter

**Comment by dmwit** [comment]
Ah. I had seen PeterJones on the list and mistakenly thought that was you. Should be fixed up now.

**Comment by peti** [comment]
Alright, now I see myself in the list of maintainers on Hackage. Thank you very much!
