### ISSUE TITLE
Hackage documentation is broken because of build error

### ISSUE THREAD

**Issue by dreamsmasher** [xmonad/X11#70]
Hi, I'm trying to write a project that depends on X11, but the documentation on Hackage is currently broken. A quick look at the [build logs](https://hackage.haskell.org/package/X11-1.9.2/reports/3) shows that the CI is failing on `cabal configure`. For some reason, `X11/extensions/Xrandr.h` isn't being correctly found by `cabal` even though .travis.yml installs it. All the docs are missing because of this.

`configure.ac` makes use of AC_PATH_EXTRA, which should find the correct header files. I don't know if it's an error on Travis CI's part or a bug. This project configures and builds fine on my system.

**Comment by geekosaur** [comment]
Presumably we need a corresponding `extra-include-dirs` to go with the `extra-lib-dirs` — but then there's #73 which may follow from one or both.

**Comment by dreamsmasher** [comment]
Update:

The docs are fixed now as of #69. Thank you to everyone involved, now I can write my trash window manager with confidence B)
