### ISSUE TITLE
`waitForEvent dpy 0` eventually waits indefinitely

### ISSUE THREAD

**Issue by aforemny** [xmonad/X11#99]
Hi!,

I am having an issue with the `waitForEvent` function that I don't understand: even if I specify a low timeout, eventually it blocks for an indefinite amount of time.

Consider the following program that waits for X events in a loop and consumes them as they become available. While waiting, it prints the number of times `waitForEvent` returns to standard output.

```haskell
module Main where

import Control.Monad
import Graphics.X11
import System.IO

main = do
  dpy <- openDisplay ""
  let loop n e = do
        putStr ("\r" <> show n) >> hFlush stdout
        isTimeOut <- waitForEvent dpy 0
        when (not isTimeOut) (print =<< nextEvent dpy e)
        loop (n + 1) e
  allocaXEvent $ loop 0
```

I compiled this program using `ghc Test.hs`. The program reliably counts to some number (usually 6291 in my case, but I have found it to vary), and then hangs. Using strace on the process I see the following calls to `pselect`:

```
pselect6(5, [4], [], [], {tv_sec=0, tv_nsec=0}, NULL) = 0 (Timeout)
[..]
pselect6(5, [4], [], [], {tv_sec=283467841536, tv_nsec=0}, NULL
```

I am testing on x86_64 Linux, kernel 6.1.78 using ghc 9.4.8 and X11 1.10.3. Haskell X11 is linked against libX11 1.8.7, and I am running X server 1.21.1.11.

I would appreciate any feedback, as I am at a loss on how to continue debugging this.

Thanks!

**Comment by geekosaur** [comment]
It looks like the original author of the X11 package assumed `struct timeval` contains 32-bit quantities, but they're actually 64 bits. This means the upper bits can contain garbage.

**Comment by geekosaur** [comment]
Notably, it looks to me like the lower 32 bits of `tv_sec` are 0 as expected, but the upper 32 bits aren't.

**Comment by geekosaur** [comment]
The complication here is we may still need to support platforms where `tv_sec` is `time_t` (32 bits). Not sure how we deal with this, especially when we can't rely on it using glibc (we still have NetBSD users, I think). Probably something in `hsc2hs`?

**Comment by liskin** [comment]
There's probably something we can #if on?
(too sick to open a computer so not looking into it any further now, sorry)

**Comment by geekosaur** [comment]
I'm not finding anything portable, aside from doing it in `configure`. _But_, it seems the `unix` package assumes it's `CLong`, so we might as well do so too.

**Comment by geekosaur** [comment]
Okay, in the interests of not forcing a PVP break, I left `waitForEvent` with the same type; but it should at some point change to either `Word64` or `CLong`.

**Comment by slotThe** [comment]
Why are following PVP? :)

**Comment by geekosaur** [comment]
You'll want to depend on `X11 ^>= 1.10.3.10`, although that version isn't on Hackage yet so you'll have to vendor it for now.
